# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.5'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Barlytics' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # Fix readlink in CocoaPods framework scripts (Xcode 14.3+ / macOS compatibility)
    Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', '**', '*-frameworks.sh')).each do |script_path|
      script = File.read(script_path)
      if script.include?('readlink "${') && !script.include?('readlink -f "${')
        File.write(script_path, script.gsub('readlink "${', 'readlink -f "${'))
      end
    end
  end
end
